apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "app.fullname" . }}-traefik
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "app.fullname" . }}-traefik
                port:
                  number: 80