# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

mainService:
  image:
    repository: fenkss/php-app
    tag: "latest"
    pullPolicy: Always
  type: NodePort
  port: 80
  develop:
    enabled: false
    pwd: "/hosthome/fenk/projects/apigateway/php/app"

authService:
  image:
    repository: fenkss/auth-app
    tag: "latest"
    pullPolicy: Always
  type: ClusterIP
  port: 80
  develop:
    enabled: false
    pwd: "/hosthome/fenk/projects/apigateway/auth/app"

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 5Gi
  storageClass: standard

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  fullnameOverride: "app-mysql"
  auth:
    password: "1"
    rootPassword: "1"
    username: "app"
    database: "app"

traefik:
  providers:
    kubernetesIngress:
      enabled: false # Настраиваем маршруты только с помощью CRD (IngressRoute)
  ports:
    websecure:
      expose: false # Выключаем https
  logs:
    access:
      enabled: true
    general:
      level: DEBUG
