apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-nginx
  labels:
    app: {{ template "app.fullname" . }}-nginx
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  default.conf: |-
    upstream php-fpm {
        server 127.0.0.1:9000;
    }
    proxy_intercept_errors on;
    fastcgi_intercept_errors on;
    server {
        server_name _;
        root /var/www/app/public;
        listen 80;

        #location ~ .(css|img|js|ico|jpg|png)$ {
        #    try_files $uri =404;
        #}
        location / {
            # try to serve file directly, fallback to app.php
            try_files $uri /index.php$is_args$args;
        }

        # DEV
        # This rule should only be placed on your development environment
        # In production, don't include this and don't deploy index_dev.php or config.php
        location ~ ^/(index_dev|config)\.php(/|$) {
            #fastcgi_pass unix:/var/run/php7.4-fpm.sock;
            fastcgi_pass php-fpm;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
        }
        # PROD
        location ~ ^/index\.php(/|$) {
            fastcgi_pass php-fpm;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;

           fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
           fastcgi_param DOCUMENT_ROOT $realpath_root;
           # Prevents URIs that include the front controller. This will 404:
           # http://domain.tld/app.php/some-path
           # Remove the internal directive to allow URIs like this
           internal;
       }

       # return 404 for all other php files not matching the front controller
       # this prevents access to other php files you don't want to be accessible.
       location ~ \.php$ {
         return 404;
       }

       error_log /var/log/nginx/error.log;
       access_log /var/log/nginx/access.log;
    }