{{ if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.fullname" . }}
spec:
  storageClassName: {{.Values.persistence.storageClass}}
  accessModes:
    - {{.Values.persistence.accessMode}}
  resources:
    requests:
      storage: {{.Values.persistence.size}}
{{end}}