{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: {{ template "app.auth" . }}*/}}
{{/*  annotations:*/}}
{{/*    nginx.ingress.kubernetes.io/rewrite-target: /$2*/}}
{{/*spec:*/}}
{{/*  rules:*/}}
{{/*    - #host: arch.homework*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          - path: /auth(/|$)(.*)*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ template "app.auth" . }}*/}}
{{/*                port:*/}}
{{/*                  number: 80*/}}