apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.auth" . }}
  labels:
    name: {{ include "app.auth" . }}
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.authService.type }}
  ports:
    - port: {{ .Values.authService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ include "app.auth" . }}
    {{- include "app.selectorLabels" . | nindent 4 }}
